### PR TITLE
[FIX] account_ux

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/336).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@fw-bot-adhoc ignore

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Pull request closed without merging**
