### PR TITLE
[IMP] account_payment_term_surcharge: Added restriction setting payme…

### PR DESCRIPTION
**Pull request by feg-adhoc**
…nt term surcharge

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/590).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r-

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
