### PR TITLE
[FW][FIX] account_ux: delete draft vendor bill

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 55058
This pr replaces https://github.com/odoo/odoo/pull/100728 

Description of the issue/feature this PR addresses:

On Runbot Odoo enterprise v15.0 install l10n_ar_edi module (Argentina Electronic Invoicing).

Select and work on "(AR) Responsable Inscripto" Company.

Go to Accounting > Vendor > Bills.

Create a Vendor bill with vendor "ADHOC SA", document number 1-5 (this is an example), and save.

Try to delete de bill, a see the sequence problem. "User Error: You cannot delete this entry, as it has already consumed a sequence number and is not the last one in the chain. You should probably revert it instead."

Current behavior before PR:
Can't delete draft vendor bill situated in a company from l10n_ar localization.

Desired behavior after PR is merged:
Is possible to delete draft vendor bills situated in a company from l10n_ar localization.

Forward-Port-Of: ingadhoc/account-financial-tools#429

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/462).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral cherrypicking of pull request ingadhoc/account-financial-tools#429 failed.

stdout:
```
Auto-merging account_ux/models/account_move.py
CONFLICT (content): Merge conflict in account_ux/models/account_move.py

```

stderr:
```
20:12:19.171007 git.c:444               trace: built-in: git cherry-pick aec79ed98d0dd992c388ecae0f33bbeacc3b27bc
error: could not apply aec79ed9... [FIX] account_ux: delete draft vendor bill
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
not necessary this fix in 16

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was closed then reopened. It should be merged the normal way (via @roboadhoc)

**Pull request closed without merging**
