### PR TITLE
[ADD] account_payment_term_surcharge: new module

### PR DESCRIPTION
**Pull request by zaoral**
The new module to add surcharge in payment term and generate surcharge invoices

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/388).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#392

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#392

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#392

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#392

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#392

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#392

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#392

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#392

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#392

**Pull request closed without merging**
