### PR TITLE
[FW][REM] account_ux: Moved action_reoncile to account_accountant_ux

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-financial-tools#584

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/586).

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @cav-adhoc cherrypicking of pull request ingadhoc/account-financial-tools#584 failed.

stdout:
```
Auto-merging account_ux/views/account_move_line_views.xml
Auto-merging account_ux/__manifest__.py
CONFLICT (content): Merge conflict in account_ux/__manifest__.py

```

stderr:
```
12:14:37.869731 git.c:444               trace: built-in: git cherry-pick ab59229e2c5ab46d3fa5df4cb4d05c2d38ed280a
error: could not apply ab59229e... [DEL] account_ux: Moved action_reoncile to account_accountant_ux
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@feg-adhoc @cav-adhoc linked pull request(s) ingadhoc/odoo-argentina-ee#481 not ready. Linked PRs are not staged until all of them are ready.

**Pull request closed without merging**
