### PR TITLE
[FIX] account_validate_account_move: send mail on validated invoices.

### PR DESCRIPTION
**Pull request by zaoral**
ticket 36113

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/343).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc r-

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
