### PR TITLE
[FW][FIX] account_interest: Fix in analytic line ids for invoice line

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-financial-tools#508

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/510).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @jjscarafia this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @jjscarafia this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@rov-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
