### PR TITLE
[IMP] account_ux: duplicated groups

### PR DESCRIPTION
**Pull request by zaoral**
ticket 47202 / 46214 / 46711
---

Improve the found possible duplicated ir.action.server

* now we show both the duplicated and the original transactions.
* We show the duplicated grouped by group of duplicate
* we add there filters that help the user to review the duplicated groups

   * Default group by Duplicated Group
   * Filter by Reconciled
   * Filter by Not Reconciled

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/320).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#324

**Pull request closed without merging**
