### PR TITLE
[MIG] account_statement_aeroo_report: Migration to 16.0

### PR DESCRIPTION
**Pull request by mem-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/372).

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @mem-adhoc: you can't review+.

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
