### PR TITLE
[FIX] account_ux: fix in release

### PR DESCRIPTION
**Pull request by zaoral**
because this change https://github.com/odoo/odoo/pull/164208/

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/516).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@zaoral @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#517

**Comment by fw-bot-adhoc** [comment]
@zaoral @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#517

**Comment by fw-bot-adhoc** [comment]
@zaoral @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#517

**Comment by fw-bot-adhoc** [comment]
@zaoral @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#517

**Comment by fw-bot-adhoc** [comment]
@zaoral @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#517

**Comment by fw-bot-adhoc** [comment]
@zaoral @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#517

**Comment by fw-bot-adhoc** [comment]
@zaoral @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#517

**Comment by fw-bot-adhoc** [comment]
@zaoral @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#517

**Comment by fw-bot-adhoc** [comment]
@zaoral @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#517

**Pull request closed without merging**
