### PR TITLE
[FW][FIX] account_payment_term_surcharge: Correct calculation of next_surcharge_date with day_current_month

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
This fix addresses an issue when calculating `next_surcharge_date` for surcharges that depend on a specific day of the current month. For example, if the invoice date is 30/11 and the surcharge is set for the 13th of the month, the calculated `next_surcharge_date` was incorrectly set to 13/11 (a past date).

With this fix, the calculation ensures the `next_surcharge_date` is properly set to 13/12 (the next valid occurrence).

Forward-Port-Of: ingadhoc/account-financial-tools#606

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/607).

**Comment by fw-bot-adhoc** [comment]
This PR targets 17.0 and is part of the forward-port chain. Further PRs will be created up to 18.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
