### PR TITLE
[FIX] account_ux: Corrección del campo notas internas en vista de facturas

### PR DESCRIPTION
**Pull request by mem-adhoc**
Ticket: 59774

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/389).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc r-

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@zaoral you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
runbot is red because of another external error related to autocomplete module https://runbot.adhoc.ar/runbot/batch/6442/build/8868
That is why we force the merging.
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
