### PR TITLE
[FIX] account_interests: change domain

### PR DESCRIPTION
**Pull request by ica-adhoc**
partner.active isn't a field and causes an error, partner_id.active is the correct form

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/397).

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#398

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#406

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#406

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#406

**Pull request closed without merging**
