### PR TITLE
[IMP] account_ux: change journal when changing pay type

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/495).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#497

**Pull request closed without merging**
