### PR TITLE
[FW][FIX]account_debt_report: corregir importes en Detalle de Deuda

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket 53861

Forward-Port-Of: ingadhoc/account-financial-tools#357

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/358).

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
This PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by zaoral** [comment]
rebase, verify the name od the fields in 15. and then merge

**Comment by pablohmontenegro** [comment]
[@fw-bot-adhoc](https://github.com/fw-bot-adhoc) ni [@roboadhoc](https://github.com/roboadhoc) override=ci/oba_without_tests override=ci/argentina-ee

**Comment by pablohmontenegro** [comment]
@roboadhoc r+ override=ci/oba_without_tests p=0

**Comment by roboadhoc** [comment]
@pablohmontenegro you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Pull request closed without merging**
