### PR TITLE
[18.0][MIG] Migration account_debt_report for Odoo 18

### PR DESCRIPTION
**Pull request by adrianpaesani**
#### Description
This PR migrates the `account_debt_report` module to ensure compatibility with Odoo 18. Additionally, unit tests have been added to validate the core functionality and key wizard actions.

#### Changes made
1. **Manifest file (`__manifest__.py`)**:
   - Updated the module version to `"18.0.1.0.0"`.
   - Set `installable` to `True` to allow installation in Odoo 18.

2. **Addition of Unit Tests**:
   - Created `tests/test_account_debt_report.py` to add basic tests for core functionality:
     - **Test for `_get_debt_report_lines`**: Verifies that this method returns a list of report lines as expected, and each line includes the fields `date`, `name`, and `balance`.
     - **Wizard Tests**:
       - `test_confirm_method`: Confirms that the `confirm` method generates the report action as expected.
       - `test_send_by_email_method`: Verifies that the `send_by_email` method returns the expected action window (`mail.compose.message`) for email composition.

#### Tests Performed
This PR includes unit tests that cover:
- Basic functionality of `account_debt_report` line generation.
- Actions within the wizard, including report confirmation and email sending.

#### Closes Issue(s)
This PR does not close any specific issues but addresses compatibility of `account_debt_report` with Odoo 18.

@maq-adhoc

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/585).

**Comment by cav-adhoc** [comment]
@adrianpaesani Hola! Lo veo bien! podrías hacer un rebase para que quede al día con el código actual? Gracias!!

**Comment by rov-adhoc** [comment]
@adrianpaesani Hola! perdon nuevamente la molestia! pero podras realizar un rebase asi ya lo apruebo? gracias

**Comment by adrianpaesani** [comment]
Listo @rov-adhoc cualquier cosa me avisas y lo vuelvo a hacer, no hay problema, hacemos los rebase que sean necesarios

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@adrianpaesani @rov-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by rov-adhoc** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
I'm sorry, @rov-adhoc: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
@adrianpaesani @rov-adhoc unable to stage: commits with multiple parents (9f3e9f235871426cbdb71a858889b370c34d156d) can not be rebased, either fix the branch to remove merges or merge without rebasing

**Comment by rov-adhoc** [comment]
@adrianpaesani buen dia! podras hacer un squash de los dos commit que quedaron? dejando con el que persite el siguiente "[[18.0][MIG] Migration and update of account_debt_report for Odoo 18](https://github.com/ingadhoc/account-financial-tools/pull/585/commits/bc8b7f7800442da096ed1c82c5caaf91a39e5507)"

**Comment by cav-adhoc** [comment]
@adrianpaesani Hola! me llegó un mail que dice pushed 0 commits, creo que no se hizo bien el squash (no nos deja mezclarlo si tiene más de un commit, por eso la insistencia 😅)

**Comment by adrianpaesani** [comment]
> @adrianpaesani Hola! me llegó un mail que dice pushed 0 commits, creo que no se hizo bien el squash (no nos deja mezclarlo si tiene más de un commit, por eso la insistencia 😅)

No me daba mas opciones la interfaz de github, con los squash siempre me complico ja, avisame si quedo bien esta vez @rov-adhoc

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by cav-adhoc** [comment]
@adrianpaesani Mezclado! Gracias por contribuir!!

**Pull request closed without merging**
