### PR TITLE
[FW][FIX] account_debt_report: invoice detail on debt report

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 55619

Forward-Port-Of: ingadhoc/account-financial-tools#360

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/361).

**Comment by fw-bot-adhoc** [comment]
Ping @mem-adhoc, @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @mem-adhoc, @zaoral

ci/oba_without_tests failed on this forward-port PR

**Comment by zaoral** [comment]
rebease, and merge

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by mem-adhoc** [comment]
@roboadhoc override=ci/oba_without_tests  override=ci/argentina-ee r+

**Comment by roboadhoc** [comment]
I'm sorry, @mem-adhoc:
- you are not allowed to override this status.
- you are not allowed to override this status.
- I must know your email before you can review PRs. Please contact an administrator.

**Comment by mem-adhoc** [comment]
@nicomacr Nico buenos días. Nos puedes ayudar a mezclar este PR ?, ya lo revisamos y esta todo ok pero esta todo en rojo por un rojo que esta en el build principal de 15.0 y no tenemos permiso para mezclar.

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request closed without merging**
