### PR TITLE
Revert "[I18N] Update translation terms from Transifex adhoc-odoo-15-0"

### PR DESCRIPTION
**Pull request by nicomacr**
This reverts commit db9553185f1d98a182ae6771ec899e0aeaa467cf.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/337).

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/argentina-ee

**Comment by roboadhoc** [comment]
@nicomacr, you may want to rebuild or fix this PR as it has failed CI.

**Pull request closed without merging**
