### PR TITLE
[FW][FIX] account_interests: posted move in domain

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
ticket 63768

Forward-Port-Of: ingadhoc/account-financial-tools#433

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/434).

**Comment by fw-bot-adhoc** [comment]
This PR targets 15.0 and is part of the forward-port chain. Further PRs will be created up to 16.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc the next pull request (ingadhoc/account-financial-tools#435) is in conflict. You can merge the chain up to here by saying
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Pull request closed without merging**
