### PR TITLE
[FW][MIG] account_payment_term_surcharge: Migration to 16.0

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-financial-tools#440

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/460).

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
cierro el pr, vamos a seguir evaluar si es necesario en tarea de migra a 17 #37307

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this PR was closed then reopened. It should be merged the normal way (via @roboadhoc)

**Pull request merged**
