### PR TITLE
[MIG] account_journal_security: Migration to 17.0

### PR DESCRIPTION
**Pull request by pablohmontenegro**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/475).

**Comment by jjscarafia** [comment]
@roboadhoc rebase-ff

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
