### PR TITLE
[IMP] account_interests: discriminate active partners

### PR DESCRIPTION
**Pull request by ica-adhoc**
Now the cron to create interest invoices filters active partners

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/384).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#385
- ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#386

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#386

**Pull request closed without merging**
