### PR TITLE
[FW][REF] account_interests: make module more inheritable

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
ticket 56082

Forward-Port-Of: ingadhoc/account-financial-tools#362

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/364).

**Comment by fw-bot-adhoc** [comment]
Ping @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @zaoral

ci/oba_without_tests failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
This PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
