### PR TITLE
[FW][FIX] account_debt_report: ods report correction

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
diviza to divisa on ods report

Forward-Port-Of: ingadhoc/account-financial-tools#422

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/424).

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this PR targets 16.0 and is the last of the forward-port chain containing:
* ingadhoc/account-financial-tools#423

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @mem-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
