### PR TITLE
[FW][FIX] account_ux: Found possible duplicates

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
ticket 48922
---

Should only be applied to statement lines on the same journal. Before this change, we were wrongly suggestion duplicated because we were searching across journals.

Forward-Port-Of: ingadhoc/account-financial-tools#329

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/349).

**Comment by fw-bot-adhoc** [comment]
Ping @zaoral cherrypicking of pull request ingadhoc/account-financial-tools#329 failed.

stdout:
```
Auto-merging account_ux/__manifest__.py
CONFLICT (content): Merge conflict in account_ux/__manifest__.py

```

stderr:
```
18:00:59.042318 git.c:439               trace: built-in: git cherry-pick 67295820abafacc47274ac535df24c30e76c5298
error: could not apply 67295820... [FIX] account_ux: Found possible duplicates
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc r-

**Comment by zaoral** [comment]
rebase, functional test, and merge

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
