### PR TITLE
[FIX] account_interests: add ',' on domain

### PR DESCRIPTION
**Pull request by ica-adhoc**
ticket 63768

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/437).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#438

**Pull request closed without merging**
