### PR TITLE
[FW][FIX] account_validate_account_move: send mail on validated invoices.

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
ticket 36113

Forward-Port-Of: ingadhoc/account-financial-tools#343

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/346).

**Comment by fw-bot-adhoc** [comment]
Ping @zaoral cherrypicking of pull request ingadhoc/account-financial-tools#343 failed.

stdout:
```
Auto-merging account_ux/wizards/account_validate_account_move.py
CONFLICT (content): Merge conflict in account_ux/wizards/account_validate_account_move.py

```

stderr:
```
23:44:02.037372 git.c:439               trace: built-in: git cherry-pick 17264d3a611ccbe07d695a455a944ec8266b7f72
error: could not apply 17264d3a... [FIX] account_validate_account_move: send mail on validated invoices.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by zaoral** [comment]
@roboadhoc r+
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
@zaoral, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral. You are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc p=1

**Pull request closed without merging**
