### PR TITLE
[FW][FIX] account_debt_report: invoice detail on debt report

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 55619

Forward-Port-Of: ingadhoc/account-financial-tools#361
Forward-Port-Of: ingadhoc/account-financial-tools#360

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/374).

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by mem-adhoc** [comment]
@nicomacr Hola Nico buenos tardes, hubo un error de configuración a la hora de construir la build en runbot, me podrías ayudar por favor ?

**Comment by zaoral** [comment]
@roboadhoc retry

**Comment by nicomacr** [comment]
@roboadhoc retry

**Comment by zaoral** [comment]
@roboadhoc r-

**Comment by nicomacr** [comment]
@roboadhoc retry

**Comment by nicomacr** [comment]
@roboadhoc r-

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/374).

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral. I'm afraid I can't do that.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. I'm afraid I can't do that.

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral. I'm afraid I can't do that.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. I'm afraid I can't do that.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. I'm afraid I can't do that.

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral. I'm afraid I can't do that.

**Comment by zaoral** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@zaoral I can only do this on forward-port PRs and this is not one, see roboadhoc.

**Comment by nicomacr** [comment]
@zaoral try again to roboadhoc and r+, I've added the rights for this repo now

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
> @zaoral try again to roboadhoc and r+, I've added the rights for this repo now

thank you @nicomacr

**Pull request closed without merging**
