### PR TITLE
[FW][IMP] account_ux: duplicated groups

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
ticket 47202 / 46214 / 46711
---

Improve the found possible duplicated ir.action.server

* now we show both the duplicated and the original transactions.
* We show the duplicated grouped by group of duplicate
* we add there filters that help the user to review the duplicated groups

   * Default group by Duplicated Group
   * Filter by Reconciled
   * Filter by Not Reconciled

Forward-Port-Of: ingadhoc/account-financial-tools#320

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/324).

**Comment by fw-bot-adhoc** [comment]
Ping @zaoral cherrypicking of pull request ingadhoc/account-financial-tools#320 failed.

stdout:
```
Auto-merging account_ux/views/account_bank_statement_views.xml
CONFLICT (modify/delete): account_ux/models/account_bank_statement_line.py deleted in HEAD and modified in c3912e0b... [IMP] account_ux: duplicated groups. Version c3912e0b... [IMP] account_ux: duplicated groups of account_ux/models/account_bank_statement_line.py left in tree.
Auto-merging account_ux/__manifest__.py
CONFLICT (content): Merge conflict in account_ux/__manifest__.py

```

stderr:
```
14:19:54.477433 git.c:439               trace: built-in: git cherry-pick c3912e0b7dc75593af022af2a55a9c1ba918c3d3
error: could not apply c3912e0b... [IMP] account_ux: duplicated groups
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
