### PR TITLE
[FW][IMP] account_interest: Add try and catch in order to be aware of the…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
… companies where the cron fail

Forward-Port-Of: ingadhoc/account-financial-tools#527

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/533).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @jjscarafia cherrypicking of pull request ingadhoc/account-financial-tools#527 failed.

stdout:
```
Auto-merging account_interests/models/res_company_interest.py
CONFLICT (content): Merge conflict in account_interests/models/res_company_interest.py

```

stderr:
```
14:49:05.292994 git.c:444               trace: built-in: git cherry-pick cfcb3389e98cba1baea4bfce475bdc26adb891b7
error: could not apply cfcb3389... [IMP] account_interest: Add try and catch in order to be aware of the companies where the cron fail
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
