### PR TITLE
[IMP] reagregamos para que el grupo  account.group_account_invoice al…

### PR DESCRIPTION
**Pull request by maq-adhoc**
… campo journal_id tambien pueda cambiar el diario de facturacion

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/453).

**Review by ica-adhoc — APPROVED** [review]

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#487

**Pull request closed without merging**
