### PR TITLE
[FW][FIX] account_interess: allow multi-line

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-financial-tools#312

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/313).

**Comment by fw-bot-adhoc** [comment]
Ping @augusto-weiss, @nicomacr
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by nicomacr** [comment]
@fw-bot-adhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/argentina-ce

**Pull request closed without merging**
