### PR TITLE
[FIX] account_payment_term_surcharge: float_round

### PR DESCRIPTION
**Pull request by ica-adhoc**
ticket 64738

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/445).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc r-

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: this PR is already reviewed, reviewing it again is useless.

**Pull request merged**
