### PR TITLE
[FW][IMP] reagregamos para que el grupo  account.group_account_invoice al…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
… campo journal_id tambien pueda cambiar el diario de facturacion

Forward-Port-Of: ingadhoc/account-financial-tools#453

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/487).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc cherrypicking of pull request ingadhoc/account-financial-tools#453 failed.

stdout:
```
Auto-merging account_ux/views/account_move_views.xml
Auto-merging account_ux/__manifest__.py
CONFLICT (content): Merge conflict in account_ux/__manifest__.py

```

stderr:
```
12:30:12.600093 git.c:444               trace: built-in: git cherry-pick 6fa682fd5690d5e0be4f507eb130158c107b4f1e
error: could not apply 6fa682fd... [IMP] reagregamos para que el grupo  account.group_account_invoice al campo journal_id tambien pueda cambiar el diario de facturacion
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by maq-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by maq-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
