### PR TITLE
[IMP]account_ux:prevent currency change when the invoice is not draft

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 51808

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/341).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc p=1

**Comment by zaoral** [comment]
@nicomacr 
Hi Mico. Hope you are doing well
I think maybe we are having a problem with runbot.
you can check this comment, it seems it was in a loop when trying to stage.

Forcing the pr with the priority it seems like resolved the problem, but not sure.
Leave here the mention in order to have it into account if you know that a recent change to runbot may has cause this or if you have any other case similar to this in the next few days.

Best Regards

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#378

**Pull request closed without merging**
