### PR TITLE
[FW][FIX] account_payment_term_surcharge: fwport

### PR DESCRIPTION
**Pull request by ica-adhoc**
ticket 64738
[manual forwardport of this](https://github.com/ingadhoc/account-financial-tools/pull/445)

### CODE REVIEW

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/448).

**Comment by roboadhoc** [comment]
@ica-adhoc @nicomacr I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#449

**Pull request closed without merging**
