### PR TITLE
[FW][ADD] account_ux: add optional ref in

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
account.view_account_payment_tree

Forward-Port-Of: ingadhoc/account-financial-tools#476

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/477).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @ica-adhoc cherrypicking of pull request ingadhoc/account-financial-tools#476 failed.

stdout:
```
CONFLICT (add/add): Merge conflict in account_ux/views/account_payment_views.xml
Auto-merging account_ux/views/account_payment_views.xml
Auto-merging account_ux/__manifest__.py
Auto-merging account_ux/README.rst

```

stderr:
```
18:25:29.151212 git.c:444               trace: built-in: git cherry-pick 18d961f418dc0f88e3cdcc2bcdd10d27b0177259
error: could not apply 18d961f4... [ADD] account_ux: add optional ref in
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
