### PR TITLE
[FW][IMP] account_interests: discriminate active partners

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Now the cron to create interest invoices filters active partners

Forward-Port-Of: ingadhoc/account-financial-tools#384

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/386).

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this PR targets 16.0 and is the last of the forward-port chain containing:
* ingadhoc/account-financial-tools#385

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
