### PR TITLE
[FW][ADD] account_payment_term_surcharge: new module

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
The new module to add surcharge in payment term and generate surcharge invoices

Forward-Port-Of: ingadhoc/account-financial-tools#388

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/391).

**Comment by fw-bot-adhoc** [comment]
This PR targets 15.0 and is part of the forward-port chain. Further PRs will be created up to 16.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
