### PR TITLE
[MIG] account_payment_term_surcharge: Migration to 16.0

### PR DESCRIPTION
**Pull request by ica-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/440).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-financial-tools#460

**Pull request closed without merging**
