### PR TITLE
[FW][FIX] account_debt_report: debt report lines amounts

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 55504

Forward-Port-Of: ingadhoc/account-financial-tools#365

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/367).

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral

ci/oba_without_tests failed on this forward-port PR

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by roboadhoc** [comment]
@pablohmontenegro, you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
rebase to resolve external error in runbot, and merge

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@roboadhoc p=0

**Pull request closed without merging**
