### PR TITLE
[FIX] account_ux: Terms and conditions label

### PR DESCRIPTION
**Pull request by zaoral**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/411).

**Comment by zaoral** [comment]
@fw-bot-adhoc ignore

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
