### PR TITLE
[FIX] account_ux: Found possible duplicates

### PR DESCRIPTION
**Pull request by zaoral**
ticket 48922
---

Should only be applied to statement lines on the same journal. Before this change, we were wrongly suggestion duplicated because we were searching across journals.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/329).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/account-financial-tools#349

**Comment by fw-bot-adhoc** [comment]
@zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-financial-tools#376

**Pull request closed without merging**
