### PR TITLE
[FW][IMP] account_debt_report:  Company currency is optional in report

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
- Donts show Monto Diviza on cmpany currency lines
- clean Pyment group compatiblitiy code

Forward-Port-Of: ingadhoc/account-financial-tools#603

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/611).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @rov-adhoc this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @rov-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by jjscarafia** [comment]
mezclo igual ya que el error de runbot no tiene que ver con este..

**Pull request merged**
