### PR TITLE
[MIG] account_interests: Migration to 18.0

### PR DESCRIPTION
**Pull request by feg-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/582).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@feg-adhoc @maq-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
