### PR TITLE
[FW][ADD] stock_account_ux: Add stock_account_ux module

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-financial-tools#520

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/523).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @jjscarafia this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @jjscarafia ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @jjscarafia this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
